[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $BASE_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "dev"

[context.branch-deploy]
command = "hugo --gc --minify -b $BASE_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.59.1"
HUGO_ENV = "dev"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"