 
backend:
  name: github
  branch: master
  repo: albirasolutions/UOC_WebRI
  base_url: https://eh7d3mcjpg.execute-api.eu-west-1.amazonaws.com # Path to ext auth provider
  auth_endpoint: prod/auth  

media_folder: "static/img" # Media files will be stored in the repo under static/img/
public_folder: "/img"
#publish_mode: editorial_workflow
collections: # A list of collections the CMS should be able to edit
  - name: "principal"
    label: "Principal"
    files:
      - label: "CA"
        name: "ca"
        file: "content/principal/principal.ca.md"
        #format: "json"
        #extension: "json"
        create: true
        fields:
          - {label: "Títol", name: "title", widget: string}
          - label: "ambits_especialitzacio"
            name: "ambits_especialitzacio"
            widget: "list"
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
          - label: "ods"
            name: "ods"
            widget: "list"
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
              - {label: "Color", name: "color", widget: string}
          - label: "sector_productiu"
            name: "sector_productiu"
            widget: "list"
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
          - label: "centre"
            name: "centre"
            widget: list
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "valor", name: "value", widget: string}   
          - label: "Albira Content"
            name: "albiraContent"
            widget: list
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "valor", name: "value", widget: string}
      - label: "ES"
        name: "es"
        file: "content/principal/principal.es.md"
        #format: "json"
        #extension: "json"
        create: true
        fields:
          - {label: "Título", name: "title", widget: string}
          - label: "ambits_especialitzacio"
            name: "ambits_especialitzacio"
            widget: "list"
            fields:
              - {label: "Campo", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
          - label: "ods"
            name: "ods"
            widget: "list"
            fields:
              - {label: "Campo", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
              - {label: "Imagen", name: "img", widget: image}
          - label: "sector_productiu"
            name: "sector_productiu"
            widget: "list"
            fields:
              - {label: "Campo", name: "display_name", widget: string}
              - {label: "Valor", name: "value", widget: string}
          - label: "centre"
            name: "centre"
            widget: list
            fields:
              - {label: "Campo", name: "display_name", widget: string}
              - {label: "valor", name: "value", widget: string}
          - label: "Albira Content"
            name: "albiraContent"
            widget: list
            fields:
              - {label: "Camp", name: "display_name", widget: string}
              - {label: "valor", name: "value", widget: string}
      - label: "EN"
        name: "en"
        file: "content/principal/principal.en.md"
        #format: "json"
        #extension: "json"
        create: true
        fields:
          - {label: "Title", name: "title", widget: string}
          - label: "ambits_especialitzacio"
            name: "ambits_especialitzacio"
            widget: "list"
            fields:
              - {label: "Key", name: "display_name", widget: string}
              - {label: "Value", name: "value", widget: string}
          - label: "ods"
            name: "ods"
            widget: "list"
            fields:
              - {label: "Key", name: "display_name", widget: string}
              - {label: "Value", name: "value", widget: string}
              - {label: "Image", name: "img", widget: image}
          - label: "sector_productiu"
            name: "sector_productiu"
            widget: "list"
            fields:
              - {label: "Key", name: "display_name", widget: string}
              - {label: "Value", name: "value", widget: string}
          - label: "centre"
            name: "centre"
            widget: list
            fields:
              - {label: "Key", name: "display_name", widget: string}
              - {label: "Value", name: "value", widget: string}
          - label: "Albira Content"
            name: "albiraContent"
            widget: list
            fields:
              - {label: "Key", name: "display_name", widget: string}
              - {label: "Value", name: "value", widget: string}
              - {label: "Selector custom", name: "selector", widget: "selector_custom"}
          - label: "Albira Content2"
            name: "albiraContent2"
            widget: selector_custom
  - name: "cercador"
    label: "Cercador"
    folder: "content/cercador"
    format: "json-frontmatter"
    #extension : "json"
    #filter: {field: "contenttype", value: "section"}    
    #create: true
    #slug: "cercador.{{language}}"
    fields:
      - {label: title, name: title, widget: string}
      - label: ambits_especialitzacio
        name : ambits_especialitzacio
        widget : list
        fields : 
          - {label: display_name, name: display_name, widget: string }
          - {label: value, name: value, widget: string }
      - label: ods
        name : ods 
        widget: list 
        fields : 
          - { label : display_name, name: display_name, widget: string }
          - { label : value, name: value, widget: string }
          - { label : color, name : color, widget : string }
      - label: centre
        name : centre 
        widget: list
        fields : 
          - { label : display_name, name: display_name, widget: string }
          - { label : value, name: value, widget: string }
  - name: "mapa-ambits-recerca"
    label: "Mapa Ambits Recerca"
    folder: "content/mapa-ambits-recerca"
    format: "json-frontmatter"
    #extension : "json"
    #filter: {field: "contenttype", value: "section"}    
    #create: true
    #slug: "mapa-ambits-recerca.{{language}}"
    fields:
      - {label: title, name: title, widget: string}
      - label: ambits_especialitzacio
        name : ambits_especialitzacio
        widget: list
        fields : 
          - {label: display_name, name: display_name, widget: string }
          - {label: value, name: value, widget: string }
      - label: ambit
        name : ambit 
        widget: list 
        fields : 
          - { label : display_name, name: display_name, widget: string }
          - { label : value, name: value, widget: string }
          - { label : color, name : color, widget : string }
  - name: "contacte"
    label: "Contacte"
    folder: "content/contacte"
    format: "json-frontmatter"
    #extension : "json"
    #filter: {field: "contenttype", value: "section"}    
    #create: true
    #slug: "mapa-ambits-recerca.{{language}}"
    fields:
          - {label: title, name: title, widget: string}
          - label: section
            name: section
            widget: list
            fields :
              - name: form
                label: form
                widget : object
                fields :
                  - {label: form, name: form, widget: boolean}
                  - {label: name, name : name, widget: string}
                  - {label: addr_1, name: addr_1, widget: string}
                  - {label: addr_2, name: addr_2, widget: string}
                  - label: phones
                    name: phones
                    widget: list 
                    fields:
                      - {label: phone, name : phone ,widget: string}
                  - label: urls
                    name: urls
                    widget: list
                    fields:
                      - {label: url, name: url, widget: string}
          - label: motius
            name: motius
            widget: list 
            fields:
              - {label: display_name, name : display_name, widget: string}
              - {label: value, name: value, widget: string}
  - name: "solucions"
    label: "Solucions"
    files:
      - label : "CA"
        name: "ca"
        file: "content/solucions/solucions.ca.md"
        create: true
        fields:
          - {label: title, name: title, widget: string}
          - label: sectors_productius
            name : sector_productiu
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: centre
            name : centre
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: solucions_tecnologiques
            name : solucions_tecnologiques
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: patents
            name : patents 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
              - { label : img_background, name : img_background, widget : image }
          - label: serveis
            name : serveis 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: spin_offs
            name : spin_offs 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
      - label : "ES"
        name: "es"
        file: "content/solucions/solucions.es.md"
        create: true
        fields:
          - {label: title, name: title, widget: string}
          - label: sectors_productius
            name : sector_productiu
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: centre
            name : centre
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: solucions_tecnologiques
            name : solucions_tecnologiques
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: patents
            name : patents 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
              - { label : img_background, name : img_background, widget : image }
          - label: serveis
            name : serveis 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: spin_offs
            name : spin_offs 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
      - label : "EN"
        name: "en"
        file: "content/solucions/solucions.en.md"
        create: true
        fields:
          - {label: title, name: title, widget: string}
          - label: sectors_productius
            name : sector_productiu
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: centre
            name : centre
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
          - label: solucions_tecnologiques
            name : solucions_tecnologiques
            widget : list
            fields : 
              - {label: display_name, name: display_name, widget: string }
              - {label: value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: patents
            name : patents 
            widget: list 
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : color, name : color, widget : string }
              - { label : img_background, name : img_background, widget : image }
          - label: serveis
            name : serveis 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
          - label: spin_offs
            name : spin_offs 
            widget: list
            fields : 
              - { label : display_name, name: display_name, widget: string }
              - { label : value, name: value, widget: string }
              - { label : img_background, name : img_background, widget : image }
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false
      