 
backend:
  name: github # FALTA CONFIGURAR GIT Y NERTLIFY PARA QUE SE COMUNIQUEN!!!!!!!!!
  repo: albirasolutions/UOC_WebRI
  branch: master
  #base_url: https://netlify-oauth.azurewebsites.net
  #client_id: b135b68c2ba0bd0c422a
  #name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"
#publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "section"
    label: "Section"
    folder: "content"
    filter: {field: "contenttype", value: "section"}    
    create: true
    slug: "_index.{{language}}"
    fields:
      - {label: "Visible", name: "visible", widget: "boolean", default: false, required: false}
      - {label: "Content Type", name: "contenttype", widget: "hidden", default: "section"}
      - {label: "Language", name: "language", widget: "select", options: ["ca", "es", "en"]}
      - {label: "Order", name: "weight", widget: "number", default: 1}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
    meta:
      - {label: "Date", name: "date", widget: "datetime"}
    editor:
      - preview: false